### ISSUE TITLE
layout problems on microprofile.io

### ISSUE THREAD

**Issue by rsoika** [eclipse/microprofile-config#487]
Maybe you know from [this discussion](https://github.com/eclipse/microprofile-marketing/issues/224) (and [here](https://github.com/eclipse/microprofile-marketing/issues/101)) about the layout on the microprofile.io homepage. 

The reason why it the layout is so ugly seems to be a problem with a wordpress plugin. 

I think we could solve this by simply replacing the inline code fragments in the readme.adoc file like this:

    ...accessed via `ConfigProvider#getConfig()`.....

with italic style:

    ...accessed via _ConfigProvider#getConfig()_......

Should I create a pull request with those changes or did you already plan to fix this otherwise?

**Comment by kenfinnigan** [comment]
This would change the display in the README from a code type to a bold, correct?

**Comment by rsoika** [comment]
it will change the code to italic. I think this can fix the layout problems currently seen on microprofile.io. But maybe @aguibert is already working on this. It is not a problem from this github repo but from the wordpress plugin used on microprofile.io

**Comment by kenfinnigan** [comment]
It would be great if we didn't have to change how the "code" pieces look in the README to make the website display correctly

**Comment by Emily-Jiang** [comment]
It seems the plugin is the root cause. I will try to get Ryan some input on the wordpress site. Thank you @rsoika for bringing it up here!

**Comment by Emily-Jiang** [comment]
Revisit this. Changing the code to italic is ok. I would like to have this fixed in the interim. Feel free to propose a PR.

**Comment by rsoika** [comment]
hm .... the readme file still doesn't seem to have been updated :-(
